ANCHOR_PATH = 'a.naslov'
CONTENT_CLASS_SUBFORUM = 'f_tablica'
CONTENT_CLASS_THREAD = 'f_postovi2'
POST_CLASS_CODE = 'editor_code'
POST_CLASS_CONTENT = 'porukabody'
POST_CLASS_DATE = 'datum'
POST_CLASS_IMAGE = 'editor_slika'
POST_CLASS_MAIN = 'postOn'
POST_CLASS_QUOTE = 'editor_quote'
POST_PATH = 'div.post'
ROOT_URL = 'https://forum.bug.hr'

SUBFORUM_TITLES = {
  '1': ('Ostale hardverske teme', 'Hardver'),
  '2': ('Ostale softverske teme', 'Softver'),
  '3': ('Internet', 'Internet i mreže'),
  '17': ('Općenito o ICT biznisu', 'ICT Pro & Biznis'),
  '18': ('PC igre', 'Igre'),
  '19': ('Općenito o mobitelima', 'Mobiteli'),
  '20': ('Fotoaparati', 'Digitalije'),
  '21': ('Televizori', 'Digitalije'),
  '22': ('Igraće konzole', 'Igre'),
  '29': ('Razni hardverski problemi', 'Hardver'),
  '30': ('Stolna računala', 'Hardver'),
  '31': ('Prijenosna računala', 'Hardver'),
  '33': ('Procesori i MBO', 'Hardver'),
  '34': ('Grafičke kartice', 'Hardver'),
  '35': ('Monitori', 'Hardver'),
  '36': ('Kućišta i napajanja', 'Hardver'),
  '37': ('Periferija', 'Hardver'),
  '38': ('Overclocking', 'Hardver'),
  '39': ('Samogradnja - općenito', 'Samogradnja'),
  '40': ('Razni softverski problemi', 'Softver'),
  '41': ('Windows', 'Softver'),
  '42': ('Linux', 'Softver'),
  '43': ('Ostali OS-i - Unix, Solaris, Mac OS...', 'Softver'),
  '44': ('Audio i video alati', 'Softver'),
  '45': ('Uredski alati', 'Softver'),
  '47': ('Sigurnosni softver', 'Softver'),
  '48': ('Programiranje', 'Razvoj'),
  '49': ('Povezivanje na Internet', 'Internet i mreže'),
  '50': ('Razni mrežni problemi', 'Internet i mreže'),
  '51': ('Mrežni hardver', 'Internet i mreže'),
  '52': ('Mrežni softver', 'Internet i mreže'),
  '53': ('Ostale mrežne teme', 'Internet i mreže'),
  '54': ('Radna iskustva', 'ICT Pro & Biznis'),
  '55': ('ICT školovanje', 'ICT Pro & Biznis'),
  '56': ('Start-up', 'ICT Pro & Biznis'),
  '57': ('Audio i video uređaji', 'Digitalije'),
  '58': ('Videokamere', 'Digitalije'),
  '60': ('Klanovski kutak', 'Igre'),
  '61': ('Dodatna oprema za igre', 'Igre'),
  '62': ('Igre za konzole i za prijenosne konzole', 'Igre'),
  '63': ('Igre za mobitele', 'Igre'),
  '66': ('Memorije', 'Hardver'),
  '69': ('Baze podataka', 'Razvoj'),
  '70': ('Razvoj web-stranica', 'Razvoj'),
  '71': ('Tvrdi i optički diskovi', 'Hardver'),
  '74': ('Tableti', 'Digitalije'),
  '75': ('Slaganje PC konfiguracija', 'Hardver'),
  '76': ('Televizijski signal (DVB-T/C/S, IPTV, HD, 3D)', 'Digitalije'),
  '88': ('Grafički programi', 'Softver'),
  '89': ('Obrada fotografija', 'Softver'),
  '91': ('Benchmark', 'Hardver'),
  '93': ('Web igre', 'Igre'),
  '94': ('Programiranje za mobilne platforme', 'Razvoj'),
  '102': ('Igre - općenito', 'Igre'),
  '106': ('Administriranje IT sustava', 'ICT Pro & Biznis'),
  '115': ('Modding projekti', 'Samogradnja'),
  '116': ('Modding galerija', 'Samogradnja'),
  '117': ('Mobilni OS-ovi i softver za mobitele', 'Mobiteli'),
  '136': ('IT trgovine', 'ICT Pro & Biznis'),
  '138': ('Kriptovalute', 'Internet i mreže'),
  '150': ('Pametni satovi i narukvice', 'Digitalije'),
  '151': ('Samsung', 'Mobiteli'),
  '152': ('iPhone', 'Mobiteli'),
  '153': ('Xiaomi', 'Mobiteli'),
  '154': ('Huawei', 'Mobiteli'),
  '155': ('LG', 'Mobiteli'),
}
